export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    SUBTRACT_ITEM: 'SUBTRACT_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    FETCH_CART_START: 'FETCH_CART_START',
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS'
}